# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7dc489eddb2b75f5405bfcd9b3cf6614f552de52159f58f03888c770ac91c1c69600f9651bc11051ee8540416dbacef5227cea7abeddc02bf7a51c58366b42e

test:
  secret_key_base: 7e9178b8a9a87efe8fb6d75014c8b5ac114423710a822d4a6d6f0b128912eb18f40b13fdd5f29efe2002e0ce0eec3549526514ec798cbb8ac75beb3c4f2de451

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
